
server:
  port: 8000
      
eureka: 
  instance: 
    hostname: localhost
    
  client: 
    register-with-eureka: false   #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: false         #表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl: 
      defaultZone: http://localhost:8000/eureka/
#  server: 
    # 设为false，关闭自我保护
#    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
#    eviction-interval-timer-in-ms: 4000

spring:
  application:
    name: spring-cloud-eureka  
#spring:
#  profiles:
#    active: prod